### ISSUE TITLE
Support retrieval of a Collector's Recipients

### ISSUE THREAD

**Issue by mtsunsoft** [chrislott/SurveyMonkeyApiV3#3]
I need to retrieve the Recipients of a specific Collector.
Since the SurveyMonkey Api v.3 supports it with `/collectors/{id}/recipients/{id}` **and** the Recipient model class already exists, it should be relatively easy to include it.

**Comment by mtsunsoft** [comment]
I'm not able to assign this to me, but I'll get down to it, anyway.

**Comment by chrislott** [comment]
I'll add u to this project :)

**Comment by mtsunsoft** [comment]
Hey, thanks.

**Comment by mtsunsoft** [comment]
Fixed by 76b92294ab80900a5f5e5ed9621c108d6d011d1a
